### ISSUE TITLE
Issue with Debian Package dovecot-imapd

### ISSUE THREAD

**Issue by pierinh00d** [chatmail/relay#574]
Hi. Are there any issues with the Debian repositories of Chatmail? During the installation of the dovecot-imapd package, apt returns a GPG signature error:

Get:1 https://download.opensuse.org/repositories/home:/deltachat/Debian_12 ./ dovecot-core 1:2.3.21+dfsg1-3 [4515 kB]
Err:1 https://download.opensuse.org/repositories/home:/deltachat/Debian_12 ./ dovecot-core 1:2.3.21+dfsg1-3
  File has unexpected size (4516048 != 4515220). Mirror sync in progress? [IP: 134.76.12.6 443]
  Hashes of expected file:
   - SHA256:d631fe5ec5574d2d38e889b141cf8ffaab1e949fb2af306669584c3e37e37cc8
   - SHA1:efff845ff20e17d30041e125145330ad5397ddfc [weak]
   - MD5Sum:fe2f23367439220ad944bb2228d20144 [weak]
   - Filesize:4515220 [weak]
Get:2 https://download.opensuse.org/repositories/home:/deltachat/Debian_12 ./ dovecot-imapd 1:2.3.21+dfsg1-3 [1544 kB]
Err:2 https://download.opensuse.org/repositories/home:/deltachat/Debian_12 ./ dovecot-imapd 1:2.3.21+dfsg1-3
  File has unexpected size (1544256 != 1544428). Mirror sync in progress? [IP: 134.76.12.6 443]
  Hashes of expected file:
   - SHA256:834d014e8a91989f19b276cde9ae932cbda0c5461e89b506ab37ef31681e0c53
   - SHA1:4b05e9e6b866c775369360e3e9f30ddd31c976d7 [weak]
   - MD5Sum:3753644edb1682579fcd47cd42b1ee6c [weak]
   - Filesize:1544428 [weak]
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/home%3A/deltachat/Debian_12/amd64/dovecot-core_2.3.21%2Bdfsg1-3_amd64.deb File has unexpected size (4516048 != 4515220). Mirror sync in progress? [IP: 134.76.12.6 443]
   Hashes of expected file:
    - SHA256:d631fe5ec5574d2d38e889b141cf8ffaab1e949fb2af306669584c3e37e37cc8
    - SHA1:efff845ff20e17d30041e125145330ad5397ddfc [weak]
    - MD5Sum:fe2f23367439220ad944bb2228d20144 [weak]
    - Filesize:4515220 [weak]
E: Failed to fetch https://ftp.gwdg.de/pub/opensuse/repositories/home%3A/deltachat/Debian_12/amd64/dovecot-imapd_2.3.21%2Bdfsg1-3_amd64.deb File has unexpected size (1544256 != 1544428). Mirror sync in progress? [IP: 134.76.12.6 443]
   Hashes of expected file:
    - SHA256:834d014e8a91989f19b276cde9ae932cbda0c5461e89b506ab37ef31681e0c53
    - SHA1:4b05e9e6b866c775369360e3e9f30ddd31c976d7 [weak]
    - MD5Sum:3753644edb1682579fcd47cd42b1ee6c [weak]
    - Filesize:1544428 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Operating System: Debian 12.11

Thanks

**Comment by pierinh00d** [comment]
I'm closing the thread. I retried this morning and the issue has been fixed

**Comment by missytake** [comment]
https://github.com/chatmail/relay/actions/runs/15169884461/job/42657032745?pr=556 still fails?

**Comment by mothdotmonster** [comment]
Same problem is happening again right now it seems...
